name: Basic personal page generation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          npm install -g @mermaid-js/mermaid-cli

      - name: Build Website
        run: |
          mkdir -p website
          pandoc --standalone \
            --from gfm \
            --output=website/index.html \
            --template=pandoc/template.html4 \
            --css=style.css \
            --toc \
            --toc-depth=1 \
            --resource-path=. \
            --lua-filter=pandoc/diagram.lua \
            --lua-filter=pandoc/paper.lua \
            --lua-filter=pandoc/date.lua \
            --extract-media=website \
            src/index.md

      - name: Setup Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website'
      - name: Deploy to GitHub Pages
        if: github.ref_name == github.event.repository.default_branch
        id: deployment
        uses: actions/deploy-pages@v4
